#!/usr/bin/env bash
# This script updates /etc/hosts to change localhost and facebook.com IP mappings.

# Backup original hosts file
cp /etc/hosts /etc/hosts.bak

# Create a temp file
tmpfile=$(mktemp)

# Remove existing localhost and facebook.com entries
grep -v 'localhost' /etc/hosts | grep -v 'facebook.com' > "$tmpfile"

# Add new mappings
echo "127.0.0.2 localhost" >> "$tmpfile"
echo "8.8.8.8 facebook.com" >> "$tmpfile"

# Overwrite /etc/hosts with the new version
cp "$tmpfile" /etc/hosts
rm "$tmpfile"
